//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_last_created_dishes
    {
        public int ID { get; set; }
        public string DishName { get; set; }
        public string DishImage { get; set; }
        public string Area { get; set; }
        public string CategoryName { get; set; }
        public string CategoryImage { get; set; }
    }
}
