//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_tot_ingrt_per_dish
    {
        public string Dish { get; set; }
        public Nullable<int> Ingredients_Quantity { get; set; }
    }
}
